image: weboaks/node-karma-protractor-chrome

cache:
  paths:
    - node_modules/

deploy:
  stage: build
  script:
    - yarn
    - yarn test
    - yarn test-legacy
    - yarn build
    - yarn deploy
