image: weboaks/node-karma-protractor-chrome

cache:
  paths:
    - node_modules/
    - .yarn-cache/

deploy:
  stage: build
  script:
    - yarn install --pure-lockfile --cache-folder .yarn-cache
    - yarn workspaces run test
    - yarn workspaces run build
    - yarn deploy
