image: node:latest

cache:
  paths:
    - node_modules/
    - .cache/

build:
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - yarn
    - yarn deploy
