name: Deploy

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - run: yarn
    - run: yarn test
  deploy:
    name: Build and deploy
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - run: yarn
    - run: yarn deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}